@extends('partials.template')
@section('header')
    @if(isset($company->name))
   <title>{{$company->name}}</title>
   @else
   <title>LMS</title>
   @endif
@endsection
@section('content')
   @include('pages.index')
@section('scripts')
@endsection
@endsection